# Project Configuration
config:
  project_name: "ros2/rosidl_runtime_c"
  program_language: "c"
  fuzz_projects_dir: "/home/walkiiiy/RosFuzzer/fuzzing_llm_engine/external_database/rosidl_runtime_c/"
  work_dir: "/home/walkiiiy/RosFuzzer/"
  shared_dir: "/home/walkiiiy/RosFuzzer//docker_shared/"
  report_target_dir: "/linux/src/cjson"
  time_budget: "5m"

  headers:
    - "cJSON.h"
    - <stdlib.h>
    - <string.h>
    - <stdint.h>
    - <sstream>
    - <sstream>
  

llm_embedding:


# DeepSeek Analyzer Configuration
llm_analyzer:
  api_key: "sk-6ae897e391304e748b85bd4c73101a86"
  model: "deepseek-chat"
  #proxy: "http://<ip>:<port>"
  base_url: "https://api.deepseek.com/v1"
  temperature: 1.0


# DeepSeek Coder Configuration
llm_coder:
  api_key: "sk-6ae897e391304e748b85bd4c73101a86"
  model: "deepseek-coder"
  #proxy: "http://<ip>:<port>"
  base_url: "https://api.deepseek.com/v1"
  temperature: 0.7

